### ISSUE TITLE
最新打包的windows的2.9.1 exe直接报错内存出问题panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by 0day4day** [hktalent/scan4all#181]
最新打包的windows的exe直接报错内存出问题
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x7ff6f1096e37]

goroutine 4745514109 [running]:
github.com/hktalent/scan4all/lib/util.(*CheckerTools).Check(0x0, {0xc00ebab500, 0x2,

**Comment by 0day4day** [comment]
go tool pprof -seconds=10 -http=:9999 http://localhost:6060/debug/pprof/heap
[INF] Running CONNECT scan with non root privileges
[INF] Port scan starting....
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x7ff6fe02933c]

goroutine 89 [running]:
net/url.(*URL).Hostname(...)
        C:/hostedtoolcache/windows/go/1.21.4/x64/src/net/url/url.go:1144
github.com/GhostTroops/scan4all/lib/util.HoneyportDetection({0xc01b99eb27?, 0xc04edd4d20?})
        D:/a/scan4all/scan4all/lib/util/HoneypotDetection.go:44 +0x11c
github.com/GhostTroops/scan4all/pkg/naabu/v2/pkg/runner.(*Runner).MergeToFile(0xc00058b500)
        D:/a/scan4all/scan4all/pkg/naabu/v2/pkg/runner/targets.go:78 +0x525
github.com/GhostTroops/scan4all/pkg/naabu/v2/pkg/runner.(*Runner).Load(0xc00058b500)
        D:/a/scan4all/scan4all/pkg/naabu/v2/pkg/runner/targets.go:31 +0x2b
github.com/GhostTroops/scan4all/pkg/naabu/v2/pkg/runner.(*Runner).RunEnumeration(0xc00058b500)
        D:/a/scan4all/scan4all/pkg/naabu/v2/pkg/runner/runner.go:240 +0x1e5
main.main.StartScan.func2()
        D:/a/scan4all/scan4all/lib/api/main.go:85 +0x538
github.com/GhostTroops/scan4all/lib/util.DoSyncFunc.func1()
        D:/a/scan4all/scan4all/lib/util/Const.go:80 +0xd4
created by github.com/GhostTroops/scan4all/lib/util.DoSyncFunc in goroutine 1
        D:/a/scan4all/scan4all/lib/util/Const.go:71 +0x65
