### ISSUE TITLE
请帮忙看下问题，谢谢。

### ISSUE THREAD

**Issue by SkyBlueEternal** [hktalent/scan4all#28]
```
root@ubuntu:~/test# chmod 775 ./scan4all 
root@ubuntu:~/test# ./scan4all -list test-7-21.txt -v -debug
2022/07/21 18:45:11 DbName  config/scan4all_db
2022/07/21 18:45:11 unable to open database file: no such file or directory
2022/07/21 18:45:11 wait for init config files ... 
2022/07/21 18:45:11 init config files is over .
Starting Nmap 7.80 ( https://nmap.org ) at 2022-07-21 18:45 PDT
Read data files from: /usr/bin/../share/nmap
Nmap done: 0 IP addresses (0 hosts up) scanned in 0.07 seconds
           Raw packets sent: 0 (0B) | Rcvd: 0 (0B)

WARNING: No targets were specified, so 0 hosts scanned.

[INF] Running SYN scan with CAP_NET_RAW privileges
[INF] Port scan starting....
2022/07/21 18:45:11 start close cache, StopCPUProfile... 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x755bf5]

goroutine 1 [running]:
net/url.(*URL).Hostname(...)
	/opt/hostedtoolcache/go/1.18.4/x64/src/net/url/url.go:1133
github.com/hktalent/scan4all/lib.HoneyportDetection({0xc0004cc000, 0xe})
	/home/runner/work/scan4all/scan4all/lib/HoneypotDetection.go:30 +0x115
github.com/hktalent/scan4all/pkg/naabu/v2/pkg/runner.(*Runner).MergeToFile(0xc007014bd0)
	/home/runner/work/scan4all/scan4all/pkg/naabu/v2/pkg/runner/targets.go:78 +0x565
github.com/hktalent/scan4all/pkg/naabu/v2/pkg/runner.(*Runner).Load(0xc007014bd0)
	/home/runner/work/scan4all/scan4all/pkg/naabu/v2/pkg/runner/targets.go:31 +0x45
github.com/hktalent/scan4all/pkg/naabu/v2/pkg/runner.(*Runner).RunEnumeration(0xc007014bd0)
	/home/runner/work/scan4all/scan4all/pkg/naabu/v2/pkg/runner/runner.go:207 +0x245
main.main()
	/home/runner/work/scan4all/scan4all/main.go:78 +0x40f
root@ubuntu:~/test# ls
config  LICENSE  README_EN.md  README.md  scan4all  scan4all_2.6.1_linux_amd64.zip  test-7-21.txt
root@ubuntu:~/test# rm -rf config/
root@ubuntu:~/test# ./scan4all -list test-7-21.txt -v -debug
2022/07/21 18:45:41 DbName  config/scan4all_db
2022/07/21 18:45:41 unable to open database file: no such file or directory
2022/07/21 18:45:41 wait for init config files ... 
2022/07/21 18:45:42 init config files is over .
Starting Nmap 7.80 ( https://nmap.org ) at 2022-07-21 18:45 PDT
Read data files from: /usr/bin/../share/nmap
Nmap done: 0 IP addresses (0 hosts up) scanned in 0.05 seconds
           Raw packets sent: 0 (0B) | Rcvd: 0 (0B)

WARNING: No targets were specified, so 0 hosts scanned.

[INF] Running SYN scan with CAP_NET_RAW privileges
[INF] Port scan starting....
2022/07/21 18:45:42 start close cache, StopCPUProfile... 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x755bf5]

goroutine 1 [running]:
net/url.(*URL).Hostname(...)
	/opt/hostedtoolcache/go/1.18.4/x64/src/net/url/url.go:1133
github.com/hktalent/scan4all/lib.HoneyportDetection({0xc005828000, 0xe})
	/home/runner/work/scan4all/scan4all/lib/HoneypotDetection.go:30 +0x115
github.com/hktalent/scan4all/pkg/naabu/v2/pkg/runner.(*Runner).MergeToFile(0xc00708ebd0)
	/home/runner/work/scan4all/scan4all/pkg/naabu/v2/pkg/runner/targets.go:78 +0x565
github.com/hktalent/scan4all/pkg/naabu/v2/pkg/runner.(*Runner).Load(0xc00708ebd0)
	/home/runner/work/scan4all/scan4all/pkg/naabu/v2/pkg/runner/targets.go:31 +0x45
github.com/hktalent/scan4all/pkg/naabu/v2/pkg/runner.(*Runner).RunEnumeration(0xc00708ebd0)
	/home/runner/work/scan4all/scan4all/pkg/naabu/v2/pkg/runner/runner.go:207 +0x245
main.main()
	/home/runner/work/scan4all/scan4all/main.go:78 +0x40f

```

**Comment by hktalent** [comment]
@SkyBlueEternal 
Download and use this version after 10 minutes：
2.6.2

**Comment by hktalent** [comment]
apt update;apt install -yy libpcap0.8-dev
<img width="620" alt="image" src="https://user-images.githubusercontent.com/18223385/180356718-f837758d-64db-4baf-b084-56a85770cedd.png">
```
root@6d20a9be8f76:/tools/scan4all_2.6.2_linux_amd64# enableNuclei=true ./scan4all -list list.txt 
2022/07/22 03:31:08 DbName  config/scan4all_db
2022/07/22 03:31:08 wait for init config files ... 
2022/07/22 03:31:11 init config files is over .
[INF] Running SYN scan with CAP_NET_RAW privileges
[INF] Port scan starting....
[INF] Port scan over,web scan starting3.33 ....
[ERR] Could not read nuclei-ignore file: open /root/.config/nuclei/.nuclei-ignore: no such file or directory
[WRN] Found 1 templates with syntax error (use -validate flag for further examination)
[INF] Using Nuclei Templates 
[INF] Templates added in last update: 0
[INF] Templates loaded for scan: 2151
[0:00:00] | Templates: 2151 | Hosts: 0 | RPS: 0 | Matched: 0 | Errors: 0 | Requests: 0/0 (9223372036854775808%)
[INF] No results found. Better luck next time!
```
