### ISSUE TITLE
Init k-v db 不能多个进程同时开启

### ISSUE THREAD

**Issue by SkyBlueEternal** [hktalent/scan4all#39]
```
>scan4all.exe -l test-7-21-all.txt -o rus_scan4all.txt
2022/07/25 20:27:51 Init k-v db 不能多个进程同时开启 Value log truncate required to run DB. This might result in data loss
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x14a pc=0x7ff774432974]

goroutine 1 [running]:
github.com/dgraph-io/badger.(*DB).View(0x7ff7760e5d40?, 0xc000027a28)
        D:/a/scan4all/scan4all/vendor/github.com/dgraph-io/badger/txn.go:676 +0x34
github.com/hktalent/scan4all/lib/util.(*KvDbOp).Get(0x7ff775deb1eb?, {0x7ff775d153b7?, 0x7ff7770f90a0?})
        D:/a/scan4all/scan4all/lib/util/kvDb.go:74 +0x71
github.com/hktalent/scan4all/brute.init.2()
        D:/a/scan4all/scan4all/brute/fuzzAI.go:51 +0x171
```

```
>scan4all.exe -l test-7-21-all.txt -v -o rus_scan4all.txt
2022/07/25 20:27:30 Init k-v db 不能多个进程同时开启 Value log truncate required to run DB. This might result in data loss
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x14a pc=0x7ff774432974]

goroutine 1 [running]:
github.com/dgraph-io/badger.(*DB).View(0x7ff7760e5d40?, 0xc005a2fa28)
        D:/a/scan4all/scan4all/vendor/github.com/dgraph-io/badger/txn.go:676 +0x34
github.com/hktalent/scan4all/lib/util.(*KvDbOp).Get(0x7ff775deb1eb?, {0x7ff775d153b7?, 0x7ff7770f90a0?})
        D:/a/scan4all/scan4all/lib/util/kvDb.go:74 +0x71
github.com/hktalent/scan4all/brute.init.2()
        D:/a/scan4all/scan4all/brute/fuzzAI.go:51 +0x171
```

**Comment by hktalent** [comment]
每个进程启动前设置环境变量
CacheName=db1_2_n
设置不同的名字，就可以启动多个实例了，以linux为例：
```
CacheName=db1 scan4all -l test-7-21-all.txt -o rus_scan4all.txt
```
