### ISSUE TITLE
Execution error

### ISSUE THREAD

**Issue by MaTcHo00** [hktalent/scan4all#58]
Command : 
`CacheName=dby ./scan4all -host test.com -csv -o 1.csv -v`

```
Nmap done: 3 IP addresses (3 hosts up) scanned in 0.04 seconds
[INF] Port scan over,web scan starting9.17 ....
[DBG] Setting single path to "favicon.ico" and ignoring multiple paths settings
panic: interface conversion: interface is nil, not error

goroutine 3058 [running]:
github.com/hktalent/scan4all/lib/util.TestIs404({0xc0002d9aa1, 0x16})
        /home/runner/work/scan4all/scan4all/lib/util/config.go:382 +0xf8
github.com/hktalent/scan4all/projectdiscovery/nuclei_Yaml.RunNuclei(0x49cee60, 0xc000ee16e0, 0x10b45c6?, 0xc0004e5da0)
        /home/runner/work/scan4all/scan4all/projectdiscovery/nuclei_Yaml/nuclei_yaml.go:33 +0x6e5
created by github.com/hktalent/scan4all/pkg/naabu/v2/pkg/runner.(*Runner).Httpxrun.func2
        /home/runner/work/scan4all/scan4all/pkg/naabu/v2/pkg/runner/runner.go:86 +0xaa
```

**Comment by hktalent** [comment]
download latest ver
<img width="797" alt="image" src="https://user-images.githubusercontent.com/18223385/182162973-fb45e75f-5a05-468d-873c-f2679f42e39b.png">
<img width="749" alt="image" src="https://user-images.githubusercontent.com/18223385/182163069-21b00d94-946f-48a6-bf0d-a1dbf7d3301b.png">

**Comment by MaTcHo00** [comment]
@hktalent thanks,When the release version will be updated ?

**Comment by hktalent** [comment]
V 2.7.0 wait 10 minutes
